In [13]:
!pip install kache

  Created wheel for kache: filename=kache-0.1.5-py3-none-any.whl size=2679 sha256=6338fa1f01320809c3a441b0bb7ff82ae181c6e6d41f93c173eba3111d38da69
  Stored in directory: /home/spock/.cache/pip/wheels/85/00/07/634b3a9bffbd3a7a9a0ecda27cbddfc50b60bda9207e1208c2
Successfully built kache
You should consider upgrading via the '/home/spock/projects/ComputerVision/.venv/bin/python -m pip install --upgrade pip' command.


In [11]:
from scipy.optimize import linear_sum_assignment
import numpy as np

cost = np.array([[4, 1, 3],
                 [2, 0, 5]])
row_ind, col_ind = linear_sum_assignment(cost)

row_ind, col_ind

(array([0, 1]), array([1, 0]))

In [10]:
{9, 9}
{8, 11}
{4, 9, 8, 7, 7, 9, 11, 7, 10, 7, 10, 5, 9, 5, 9, 4, 7 }

array([1, 2, 2])

In [16]:
POSSIBLE_MOVES = []
for i_ in [1,2,-1,-2]:
    for j_ in [1,-1] if i_ in [2,-2] else [2,-2]:
        POSSIBLE_MOVES.append((i_,j_))
POSSIBLE_MOVES

[(1, 2), (1, -2), (2, 1), (2, -1), (-1, 2), (-1, -2), (-2, 1), (-2, -1)]

In [36]:
from kache import cache
import pandas as pd
S = 5
names = [str(i) for i in range(-S, S+1)]
M = pd.DataFrame(np.ones((S*2+1,S*2+1)), index=names, columns=names)
M*=-1
M.loc['0','0']=0
# print(M)

def cost(i,j):          
    for i_, j_ in POSSIBLE_MOVES:
        if i+i_ > S or i+i_<-S or j+j_ > S or j+j_ < -S:
            continue                
        possible_best_score = M.loc[str(i),str(j)] + 1
        if M.loc[str(i+i_),str(j+j_)] == -1 or M.loc[str(i+i_), str(j+j_)] > possible_best_score:
            M.loc[str(i+i_),str(j+j_)] = possible_best_score
            cost(i+i_, j+j_)

cost(0,0)
M 


-5   -4   -3   -2   -1    0    1    2    3    4    5
-5  4.0  3.0  4.0  3.0  4.0  3.0  4.0  3.0  4.0  3.0  4.0
-4  3.0  4.0  3.0  2.0  3.0  2.0  3.0  2.0  3.0  4.0  3.0
-3  4.0  3.0  2.0  3.0  2.0  3.0  2.0  3.0  2.0  3.0  4.0
-2  3.0  2.0  3.0  4.0  1.0  2.0  1.0  4.0  3.0  2.0  3.0
-1  4.0  3.0  2.0  1.0  2.0  3.0  2.0  1.0  2.0  3.0  4.0
0   3.0  2.0  3.0  2.0  3.0  0.0  3.0  2.0  3.0  2.0  3.0
1   4.0  3.0  2.0  1.0  2.0  3.0  2.0  1.0  2.0  3.0  4.0
2   3.0  2.0  3.0  4.0  1.0  2.0  1.0  4.0  3.0  2.0  3.0
3   4.0  3.0  2.0  3.0  2.0  3.0  2.0  3.0  2.0  3.0  4.0
4   3.0  4.0  3.0  2.0  3.0  2.0  3.0  2.0  3.0  4.0  3.0
5   4.0  3.0  4.0  3.0  4.0  3.0  4.0  3.0  4.0  3.0  4.0

In [12]:
horses = np.array([[9,9],[8,11]])
# find cost function for i,j to k,l



array([[ 9,  9],
       [ 8, 11]])